CREATE TABLE IF NOT EXISTS "aste-off_auth_account" (
	"id" varchar PRIMARY KEY NOT NULL,
	"account_id" varchar NOT NULL,
	"provider_id" varchar NOT NULL,
	"user_id" varchar NOT NULL,
	"access_token" varchar,
	"refresh_token" varchar,
	"id_token" varchar,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" varchar,
	"password" varchar,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "aste-off_brand" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "aste-off_brand_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"logo" varchar(256),
	"phone_number" integer,
	"email" varchar(256),
	"website" varchar(256)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "aste-off_job" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "aste-off_job_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"job_id" varchar(256),
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"service" varchar(256),
	"design_description" varchar(256),
	"reference_images" varchar(256),
	"design_files" varchar(256),
	"user_info" varchar(256)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "aste-off_auth_passkey" (
	"id" varchar PRIMARY KEY NOT NULL,
	"name" varchar,
	"public_key" varchar NOT NULL,
	"user_id" varchar NOT NULL,
	"credential_i_d" varchar NOT NULL,
	"counter" integer NOT NULL,
	"device_type" varchar NOT NULL,
	"backed_up" boolean NOT NULL,
	"transports" varchar,
	"created_at" timestamp
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "aste-off_auth_session" (
	"id" varchar PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" varchar NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" varchar,
	"user_agent" varchar,
	"user_id" varchar NOT NULL,
	CONSTRAINT "aste-off_auth_session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "aste-off_auth_user" (
	"id" varchar PRIMARY KEY NOT NULL,
	"name" varchar NOT NULL,
	"email" varchar NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" varchar,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "aste-off_auth_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "aste-off_auth_verification" (
	"id" varchar PRIMARY KEY NOT NULL,
	"identifier" varchar NOT NULL,
	"value" varchar NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "aste-off_auth_account" ADD CONSTRAINT "aste-off_auth_account_user_id_aste-off_auth_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."aste-off_auth_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "aste-off_job" ADD CONSTRAINT "aste-off_job_user_info_aste-off_auth_user_id_fk" FOREIGN KEY ("user_info") REFERENCES "public"."aste-off_auth_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "aste-off_auth_passkey" ADD CONSTRAINT "aste-off_auth_passkey_user_id_aste-off_auth_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."aste-off_auth_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "aste-off_auth_session" ADD CONSTRAINT "aste-off_auth_session_user_id_aste-off_auth_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."aste-off_auth_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
